### ISSUE TITLE
Not supoort for 2D data in HierarchicalClustering?

### ISSUE THREAD

**Issue by guihui** [exhuma/python-cluster#22]
```from cluster import HierarchicalClustering
def norm(u):
    return math.sqrt(sum([x * x for x in v]))
def cosine(u, v):
    return sum([x * y for x, y in zip(u, v)])
data = [[1, 2, 3, 4], [1, 2, 3, 4.001], [5, 6, 7, 8.0]]
cl = HierarchicalClustering(data, distance_function = cosine)
print cl.getlevel(5)```

===========

Traceback (most recent call last):
  File "test2.py", line 36, in <module>
    print cl.getlevel(5)
  File "/home/work/futiannan/data/env/Python/lib/python2.7/site-packages/cluster/method/hierarchical.py", line 207, in getlevel
    self.cluster()
  File "/home/work/futiannan/data/env/Python/lib/python2.7/site-packages/cluster/method/hierarchical.py", line 146, in cluster
    item_item_matrix.genmatrix(self.num_processes)
  File "/home/work/futiannan/data/env/Python/lib/python2.7/site-packages/cluster/matrix.py", line 130, in genmatrix
    row[col_index] = self.combinfunc(item, item2)
  File "/home/work/futiannan/data/env/Python/lib/python2.7/site-packages/cluster/linkage.py", line 21, in newfun
    result = fun(a, b, distance_function)
  File "/home/work/futiannan/data/env/Python/lib/python2.7/site-packages/cluster/linkage.py", line 41, in single
    result = min(distance_function(left_a, right_b),
  File "test2.py", line 31, in cosine
    return sum([x * y for x, y in zip(u, v)])
TypeError: zip argument #1 must support iteration

**Comment by guihui** [comment]
Fix.
each row being tuple works.
