### ISSUE TITLE
Test case HClusterIntegerTestCase.testMultiprocessing fails on MacOS with Python 3.8.5, 

### ISSUE THREAD

**Issue by tim-littlefair** [exhuma/python-cluster#33]
While belatedly working on requested PEP8 fixes for a PR I did in 2018, I found that on my machine (running Python 3.8.5 on MacOS 10.15.X), this test case fails with the following stack trace:

ERROR: testMultiprocessing (__main__.HClusterIntegerTestCase)
Traceback (most recent call last):
  File "cluster/test/test_hierarchical.py", line 168, in testMultiprocessing
    [new_data.extend(_) for _ in cl.getlevel(40)]
  File "/Users/tim/repositories/python-cluster/cluster/method/hierarchical.py", line 207, in getlevel
    self.cluster()
  File "/Users/tim/repositories/python-cluster/cluster/method/hierarchical.py", line 146, in cluster
    item_item_matrix.genmatrix(self.num_processes)
  File "/Users/tim/repositories/python-cluster/cluster/matrix.py", line 120, in genmatrix
    [process.start() for process in processes]
  File "/Users/tim/repositories/python-cluster/cluster/matrix.py", line 120, in <listcomp>
    [process.start() for process in processes]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'HClusterIntegerTestCase.testMultiprocessing.<locals>.<lambda>'

I have attempted converting the inline lambda expresssion in the arguments to HierarchicalClustering to a locally defined function, this results in a similar error except the last line becomes:
AttributeError: Can't pickle local object 'HClusterIntegerTestCase.testMultiprocessing.<locals>._absolute_difference'

**Comment by exhuma** [comment]
Python 2.8.5? That doesn't exist, at least not on the official Python releases page. You mean 3.8.5?

**Comment by tim-littlefair** [comment]
Yes, sorry I do.  I've corrected the text of the original comment (title was already OK).

**Comment by exhuma** [comment]
Should work now.

**Comment by tim-littlefair** [comment]
Confirmed closed on my machine.  Thanks
